ads/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = 'ads'

urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
         views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
         views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
         views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
         views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
         views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
         views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
         views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

djangoProject/urls.py
import os
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.static import serve

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
                  path('', include('ads.urls')),  # Change to ads.urls
                  path('admin/', admin.site.urls),  # Keep
                  path('accounts/', include('django.contrib.auth.urls')),  # Keep
                  url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
                  # path('', TemplateView.as_view(template_name='home/main.html')),
                  path('profile/', include('home.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/', include('django_registration.backends.one_step.urls')),
                  path('favicon.ico', serve, {
                      'path': 'favicon.ico',
                      'document_root': os.path.join(BASE_DIR, 'home/static'),
                  }
                       ),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings

    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('<int:user_id>', views.ProfileView.as_view(), name='profile'),
    path('<int:user_id>/edit', views.ProfileUpdateView.as_view(), name='profile_update'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    home_address = models.CharField(max_length=120, null=True, default='')
    phone_number = models.CharField(max_length=32, null=True, default='')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(null=True, blank=True)

home/forms.py
from django import forms
from django.core.files.uploadedfile import InMemoryUploadedFile
from ads.humanize import naturalsize
from home.models import UserProfile


class ProfileForm(forms.ModelForm):
    max_upload_limit = 2 * 256 * 256
    max_upload_limit_text = naturalsize(max_upload_limit)
    picture = forms.ImageField(required=False, label='File to Upload <= ' + max_upload_limit_text)
    upload_field_name = 'picture'

    class Meta:
        model = UserProfile
        labels = {
            'home_address': 'Your home address',
            'phone_number': 'Phone number',
        }
        fields = ['home_address', 'phone_number', 'picture']

home/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth.models import User
from .models import UserProfile
from .forms import ProfileForm


class ProfileView(LoginRequiredMixin, View):
    template_name = 'profile.html'

    def get(self, request, user_id):
        u = get_object_or_404(UserProfile, user=User.objects.get(id=user_id))
        context = {
            'user': u,
        }
        return render(request, self.template_name, context)


class ProfileUpdateView(LoginRequiredMixin, View):
    template_name = 'profile_form.html'
    success_url = reverse_lazy('home:profile')

    def get(self, request, user_id):
        pr = get_object_or_404(UserProfile, id=user_id, user=self.request.user)
        form = ProfileForm(instance=pr)
        print(form)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, user_id=None):
        pr = get_object_or_404(UserProfile, id=user_id, user=self.request.user)
        form = ProfileForm(request.POST, request.FILES or None, instance=pr)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        pr = form.save(commit=False)
        pr.save()

        return redirect(self.success_url)

home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">
    {% block head %} {% endblock %}

</head>
<body>
    {% block navbar %} {% endblock %}

<div class="container site-container">
    {% block welcome %} {% endblock %}
    {% block messages %}
        {% if messages %}
            {% for msg in messages %}
                <div class="alert alert-{{ msg.level_tag }}" role="alert">
                    {{ msg.message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endblock %}
    {% block content %}
    {% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

home/templates/base_menu.html
{% extends "base_bootstrap.html" %}
{% block navbar %}
    {% load app_tags %}

    <nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-top">
    <div class="row px-5">
      <a class="navbar-brand text-white" href="#">Ads</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      {% url 'ads' as ads %}
        <li class="nav-item {% if request.get_full_path == ads %} active {% endif %}">
                    <a href="{% url 'ads:all' %}" class="nav-link text-white">All ads</a></li>
    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'ads:ad_create' %}">Create Ad</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink"
                           role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
                        </a>
                        <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item text-white" href="{% url 'home:profile' user.id %}">Profile</a>
                            <a class="dropdown-item text-white" href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'login' %}?next={% url 'ads:all' %}" class="nav-link text-white">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'django_registration_register' %}?next={% url 'ads:all' %}"
                           class="nav-link text-white">Register</a>
                    </li>
                {% endif %}
    </ul>
  </div>
    </div>
</nav>
{% endblock %}

home/templates/profile.html
{% extends "base_menu.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}

        <div id="overlay" class="overlay text-center" onclick="document.getElementById('overlay').style.display = 'none';">
            <img id="img-overlay" src="{% if user.picture %} {{ user.picture.url }}
                                        {% else %} {% static 'no-image.jpg' %}{% endif %}" alt="">
        </div>
    <img style="width: 20%" class="rounded border border-dark ad-image" src="{% if user.picture %} {{ user.picture.url }}
                                        {% else %} {% static 'no-image.jpg' %}{% endif %}"
             alt="" onclick="document.getElementById('overlay').style.display = 'block';">
    {{ user.user.id }} {{ user.user.username }}
{% endblock %}

home/templates/profile_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-success">
    <input type="submit" value="Cancel" class="btn btn-outline-success" onclick="window.location.href='{% url 'ads:all' %}';return false;">
  </form>
</p>
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}